### ISSUE TITLE
127 error code calling mathpix#getFromEquation()

### ISSUE THREAD

**Issue by ecomaikgolf** [ekiim/vim-mathpix#1]
Info:
```
NVIM v0.4.3
Build type: Release
Plugin manager: Plug
```

I've installed the plugin using `Plug 'https://github.com/ekiim/vim-mathpix.git', { 'on': ['Img2Latex', 'Img2Text'] }` and when I do `:Img2Latex ` nvim shows that the interpreter returned the 127 code (not found in path).

Hotfix:

Writing the complete path for `mathpix_crop` in `autoload/mathpix.vim` fixes the issue (or adding it to the path):
```
function! mathpix#getFromEquation()
    -1 read ! ~/.config/nvim/plugged/vim-mathpix/bin/mathpix_crop 2>/dev/null
endfunction

function! mathpix#getFromText()
     -1 read ! ~/.config/nvim/plugged/vim-mathpix/bin/mathpix_crop text 2>/dev/null
endfunction
```

**Comment by ekiim** [comment]
I'm not entirely sure how the installation should work with other plugin managers, but as far as my understanding goes, there should be no problem installing this, as long as you make sure that the bin directory (or at least it's content), it's available in the `PATH`.
