### ISSUE TITLE
Getting null as return on buffer

### ISSUE THREAD

**Issue by n3ry7** [ekiim/vim-mathpix#2]
Just tried out your plugin and I think it is awesome!

But I could not get it to work, always get null as return on buffer, any idea how I could fix this?

**Comment by ekiim** [comment]
Did you try and run `bin/mathpix_crop`  by itself (in a shell)? 
If that part is working and returning the correct output?

**Comment by n3ry7** [comment]
Got it working, when i tried the bin/mathpix_crop in a shell i found out it was an invalid API key actually.

Thanks!

**Comment by ekiim** [comment]
Hope the tool works for your needs.

I'll add a script to validate the API credentials soon.
